export const MOCK_ARTISTS = [
  {
    id: 'mock-artist-1',
    displayName: 'HORI SHIN',
    bio: '和彫り・日本伝統刺青を専門とする彫師。15年のキャリアを持ち、龍・般若・花魁など伝統的な題材を現代的な感覚で昇華させる。',
    specialties: ['和彫り', '龍', '般若'],
    yearsOfExperience: 15,
    studio: { id: 'mock-studio-1', name: 'IREZUMI TOKYO' },
    avgRating: 4.9,
    reviewCount: 42,
    prefecture: '東京都',
    priceRange: '¥30,000〜',
  },
  {
    id: 'mock-artist-2',
    displayName: 'Yuki Tanaka',
    bio: 'ブラックアンドグレーとリアリズムを中心に活動するアーティスト。ポートレートや自然をモチーフにした繊細な作風が人気。',
    specialties: ['ブラックアンドグレー', 'リアリズム', 'ポートレート'],
    yearsOfExperience: 8,
    studio: { id: 'mock-studio-2', name: 'INK COLLECTIVE OSAKA' },
    avgRating: 4.7,
    reviewCount: 28,
    prefecture: '大阪府',
    priceRange: '¥20,000〜',
  },
  {
    id: 'mock-artist-3',
    displayName: 'SAKURA',
    bio: '韓国スタイルのミニマルタトゥーを得意とするアーティスト。繊細な線とフラワーモチーフで人気急上昇中。',
    specialties: ['韓国風', 'ミニマル', 'フラワー'],
    yearsOfExperience: 5,
    studio: { id: 'mock-studio-3', name: 'SEOUL STYLE TOKYO' },
    avgRating: 4.8,
    reviewCount: 19,
    prefecture: '東京都',
    priceRange: '¥15,000〜',
  },
  {
    id: 'mock-artist-4',
    displayName: 'DRAGON RYU',
    bio: 'アメリカントラディショナルを現代的に解釈する彫師。大胆な配色と力強いラインが特徴。',
    specialties: ['トラディショナル', 'ネオトラッド'],
    yearsOfExperience: 12,
    studio: { id: 'mock-studio-1', name: 'IREZUMI TOKYO' },
    avgRating: 4.6,
    reviewCount: 31,
    prefecture: '東京都',
    priceRange: '¥25,000〜',
  },
  {
    id: 'mock-artist-5',
    displayName: 'MIKA INK',
    bio: 'ファインライン・水彩風タトゥーのスペシャリスト。柔らかなグラデーションと繊細なタッチで独自の世界観を表現。',
    specialties: ['ファインライン', '水彩', 'ガーリー'],
    yearsOfExperience: 6,
    studio: { id: 'mock-studio-4', name: 'PASTEL STUDIO NAGOYA' },
    avgRating: 4.9,
    reviewCount: 55,
    prefecture: '愛知県',
    priceRange: '¥18,000〜',
  },
  {
    id: 'mock-artist-6',
    displayName: 'KURO TOSHI',
    bio: 'ブラックワーク・ジオメトリックを専門とするアーティスト。幾何学的なパターンと大胆な黒一色で圧倒的な存在感を放つ。',
    specialties: ['ブラックワーク', 'ジオメトリック', 'ドットワーク'],
    yearsOfExperience: 10,
    studio: { id: 'mock-studio-5', name: 'GEOMETRIC KYOTO' },
    avgRating: 4.8,
    reviewCount: 37,
    prefecture: '京都府',
    priceRange: '¥22,000〜',
  },
  {
    id: 'mock-artist-7',
    displayName: 'TOMOE',
    bio: 'ニュースクールとイラストタトゥーを得意とするアーティスト。カラフルでポップなデザインが特徴。',
    specialties: ['ニュースクール', 'イラスト', 'カラー'],
    yearsOfExperience: 7,
    studio: { id: 'mock-studio-2', name: 'INK COLLECTIVE OSAKA' },
    avgRating: 4.7,
    reviewCount: 23,
    prefecture: '大阪府',
    priceRange: '¥20,000〜',
  },
  {
    id: 'mock-artist-8',
    displayName: 'REI SUMI',
    bio: 'レタリング専門のアーティスト。日本語・英語・アラビア文字など多様な書体に対応。',
    specialties: ['レタリング', 'カリグラフィー'],
    yearsOfExperience: 9,
    studio: { id: 'mock-studio-1', name: 'IREZUMI TOKYO' },
    avgRating: 4.6,
    reviewCount: 41,
    prefecture: '東京都',
    priceRange: '¥12,000〜',
  },
];

export const MOCK_PORTFOLIOS = [
  {
    id: 'mock-p-1',
    mediaUrls: ['https://placehold.co/400x400/111827/f3f4f6?text=和彫り'],
    artistId: 'mock-artist-1',
    styleCategory: '和彫り',
    title: '龍・桜吹雪',
  },
  {
    id: 'mock-p-2',
    mediaUrls: ['https://placehold.co/400x400/1f2937/e5e7eb?text=B%26G'],
    artistId: 'mock-artist-2',
    styleCategory: 'ブラックアンドグレー',
    title: 'ポートレート',
  },
  {
    id: 'mock-p-3',
    mediaUrls: ['https://placehold.co/400x400/111827/fce7f3?text=韓国風'],
    artistId: 'mock-artist-3',
    styleCategory: '韓国風',
    title: 'ミニフラワー',
  },
  {
    id: 'mock-p-4',
    mediaUrls: ['https://placehold.co/400x400/0f172a/fbbf24?text=TRAD'],
    artistId: 'mock-artist-4',
    styleCategory: 'トラディショナル',
    title: 'イーグル',
  },
  {
    id: 'mock-p-5',
    mediaUrls: ['https://placehold.co/400x400/111827/a78bfa?text=般若'],
    artistId: 'mock-artist-1',
    styleCategory: '和彫り',
    title: '般若・炎',
  },
  {
    id: 'mock-p-6',
    mediaUrls: ['https://placehold.co/400x400/1c1917/fafaf9?text=リアリズム'],
    artistId: 'mock-artist-2',
    styleCategory: 'リアリズム',
    title: '薔薇',
  },
  {
    id: 'mock-p-7',
    mediaUrls: ['https://placehold.co/400x400/0f172a/93c5fd?text=水彩'],
    artistId: 'mock-artist-5',
    styleCategory: '水彩',
    title: '蝶々',
  },
  {
    id: 'mock-p-8',
    mediaUrls: ['https://placehold.co/400x400/0a0a0a/e5e7eb?text=GEO'],
    artistId: 'mock-artist-6',
    styleCategory: 'ジオメトリック',
    title: '六芒星',
  },
  {
    id: 'mock-p-9',
    mediaUrls: ['https://placehold.co/400x400/1e1b4b/c4b5fd?text=ILLUST'],
    artistId: 'mock-artist-7',
    styleCategory: 'ニュースクール',
    title: 'キャラクター',
  },
  {
    id: 'mock-p-10',
    mediaUrls: ['https://placehold.co/400x400/111827/d1d5db?text=LETTER'],
    artistId: 'mock-artist-8',
    styleCategory: 'レタリング',
    title: 'カリグラフィー',
  },
  {
    id: 'mock-p-11',
    mediaUrls: ['https://placehold.co/400x400/18181b/86efac?text=FINE'],
    artistId: 'mock-artist-5',
    styleCategory: 'ファインライン',
    title: 'バラ・細線',
  },
  {
    id: 'mock-p-12',
    mediaUrls: ['https://placehold.co/400x400/09090b/f9a8d4?text=MINI'],
    artistId: 'mock-artist-3',
    styleCategory: 'ミニマル',
    title: 'ミニムーン',
  },
];

export const MOCK_STUDIOS = [
  {
    id: 'mock-studio-1',
    name: 'IREZUMI TOKYO',
    slug: 'irezumi-tokyo',
    prefecture: '東京都',
    city: '渋谷区',
    description: '東京・渋谷を拠点とする老舗スタジオ。和彫りから現代スタイルまで幅広く対応する4名の彫師が在籍。',
    artistCount: 3,
    avgRating: 4.8,
    reviewCount: 114,
    specialties: ['和彫り', 'トラディショナル', 'レタリング'],
  },
  {
    id: 'mock-studio-2',
    name: 'INK COLLECTIVE OSAKA',
    slug: 'ink-collective-osaka',
    prefecture: '大阪府',
    city: '北区',
    description: '大阪・梅田のインターナショナルスタジオ。多様なスタイルと多言語対応で海外からも人気を集める。',
    artistCount: 2,
    avgRating: 4.7,
    reviewCount: 51,
    specialties: ['ブラックアンドグレー', 'リアリズム', 'ニュースクール'],
  },
  {
    id: 'mock-studio-3',
    name: 'SEOUL STYLE TOKYO',
    slug: 'seoul-style-tokyo',
    prefecture: '東京都',
    city: '新宿区',
    description: '韓国スタイルのタトゥーに特化した新宿のスタジオ。ミニマル・フラワー・ラインワークを得意とする。',
    artistCount: 1,
    avgRating: 4.8,
    reviewCount: 19,
    specialties: ['韓国風', 'ミニマル', 'フラワー'],
  },
  {
    id: 'mock-studio-4',
    name: 'PASTEL STUDIO NAGOYA',
    slug: 'pastel-studio-nagoya',
    prefecture: '愛知県',
    city: '中区',
    description: '名古屋を拠点とするファインライン・水彩専門スタジオ。女性アーティストが多く、女性のお客様に人気。',
    artistCount: 1,
    avgRating: 4.9,
    reviewCount: 55,
    specialties: ['ファインライン', '水彩', 'ガーリー'],
  },
  {
    id: 'mock-studio-5',
    name: 'GEOMETRIC KYOTO',
    slug: 'geometric-kyoto',
    prefecture: '京都府',
    city: '中京区',
    description: '京都の美意識とジオメトリックアートを融合させたスタジオ。ブラックワーク・ドットワーク専門。',
    artistCount: 1,
    avgRating: 4.8,
    reviewCount: 37,
    specialties: ['ブラックワーク', 'ジオメトリック', 'ドットワーク'],
  },
];

export const MOCK_FACILITIES = [
  {
    id: 'mock-f-1',
    name: '湯の里 草津温泉 山翠楼',
    slug: 'kusatsu-sanseiro',
    type: 'ONSEN',
    acceptanceLevel: 'COVERED_ONLY',
    prefecture: '群馬県',
    city: '吾妻郡草津町',
    address: '草津温泉 湯畑周辺',
    tattooPolicy: 'ラッシュガード・タトゥーシールで隠せばご利用いただけます。大浴場・露天風呂ともに対応可能です。',
    description: '草津温泉の湯畑そばに立地する老舗旅館。タトゥーのあるお客様も条件付きでご入浴いただけます。',
    mediaUrls: ['https://placehold.co/800x600/f5f0e8/78350f?text=草津温泉'],
    websiteUrl: null,
  },
  {
    id: 'mock-f-2',
    name: 'AQUA WELLNESS SPA 渋谷',
    slug: 'aqua-wellness-shibuya',
    type: 'GYM',
    acceptanceLevel: 'ALLOWED',
    prefecture: '東京都',
    city: '渋谷区',
    address: '渋谷区道玄坂',
    tattooPolicy: 'タトゥーのあるお客様も全面的に歓迎いたします。プール・ジャグジー・サウナすべてご利用いただけます。',
    description: '渋谷道玄坂に位置するモダンなウェルネス施設。タトゥーに対して非常にオープンなポリシーを掲げています。',
    mediaUrls: ['https://placehold.co/800x600/0c4a6e/e0f2fe?text=AQUA+SPA'],
    websiteUrl: null,
  },
  {
    id: 'mock-f-3',
    name: 'THE URBAN HOTEL 新宿',
    slug: 'the-urban-hotel-shinjuku',
    type: 'HOTEL',
    acceptanceLevel: 'ALLOWED',
    prefecture: '東京都',
    city: '新宿区',
    address: '新宿区歌舞伎町',
    tattooPolicy: 'タトゥーの有無に関わらず全てのゲストを歓迎いたします。大浴場・プールともにご利用いただけます。',
    description: '新宿歌舞伎町の中心にあるデザインホテル。多様性を重視し、タトゥーのあるゲストも気兼ねなくご滞在いただけます。',
    mediaUrls: ['https://placehold.co/800x600/1e1b4b/e0e7ff?text=THE+URBAN'],
    websiteUrl: null,
  },
];
